# Neural Architecture Search Configuration for Fast Learning YOLO Models

# Directory structure
directories:
  base_dir: "yolo_opt_results"
  best_model_dir: "best_models"
  pruned_model_dir: "pruned_models"
  quantized_model_dir: "quantized_models"
  results_dir: "results"

# Dataset configuration
dataset_path: "data.yaml"  # This will be overridden by command line

# Search space for architecture optimization
search_space:
  # Architecture parameters
  depth_mult: [0.33, 0.67]      # Lower depth for faster learning
  width_mult: [0.5, 0.75]       # Moderate width for balance
  kernel_size: [3, 5]           # Smaller kernels compute faster
  num_channels: [32, 64]        # Fewer initial channels
  resolution: [320, 416]        # Lower resolution for faster training
  
  # Advanced architecture options
  use_complex: [1, 1]           # Always use complex model (more efficient design)
  activation: [0, 1]            # Try different activations (SiLU, ReLU)
  use_cbam: [0, 1]              # Test with and without attention
  dropout_rate: [0.1, 0.3]      # Moderate dropout for regularization
  use_gating: [0, 1]            # Try with and without gating
  bottleneck_ratio: [0.5, 0.5]  # Fixed bottleneck ratio for consistency
  num_heads: [2, 4]             # Fewer attention heads
  skip_connections: [0, 2]      # Standard or residual connections for faster gradient flow
  use_eca: [0, 1]               # Try with and without ECA

# Mapping for categorical parameters
activation_mapping:
  0: "SiLU"    # Default YOLOv8 activation
  1: "ReLU"    # Simpler activation, sometimes trains faster

skip_connections_mapping:
  0: "standard"  # Standard YOLOv8 connections
  1: "dense"     # DenseNet-style connections
  2: "residual"  # ResNet-style connections

# Initial test configuration
initial_test:
  depth_mult: 0.33
  width_mult: 0.5
  kernel_size: 3
  num_channels: 32
  resolution: 320
  use_complex: true
  activation: "ReLU"
  use_cbam: false
  dropout_rate: 0.1
  use_gating: false
  bottleneck_ratio: 0.5
  num_heads: 2
  skip_connections: "standard"
  use_eca: true

# Optimization settings
optimization:
  init_points: 5
  n_iter: 15
  performance_threshold: 0.75  # Lower threshold for faster experimentation
  early_stopping: true
  patience: 3

# Training settings
training:
  epochs: 50                    # Fewer epochs for faster trials
  patience: 5                   # Early stopping patience
  optimizer: "AdamW"            # More efficient optimizer
  batch_size: 16                # Adjust based on your GPU memory
  save: true
  verbose: true
  warmup_epochs: 3              # Warmup for first few epochs
  warmup_momentum: 0.8          # Start with higher momentum
  lr0: 0.01                     # Higher initial learning rate
  lrf: 0.01                     # Lower final learning rate ratio
  use_ema: true                 # Use exponential moving average

# Data augmentation settings
augmentation:
  # YOLOv8 standard augmentations (slightly reduced)
  use_mosaic: true
  mosaic_prob: 0.8              # Slightly reduced from 1.0
  use_mixup: false              # Disable for faster learning
  use_copy_paste: false
  
  # Basic augmentations (conservative)
  hsv_h: 0.015                  # HSV Hue augmentation
  hsv_s: 0.5                    # HSV Saturation (reduced)
  hsv_v: 0.3                    # HSV Value (reduced)
  degrees: 0.0                  # No rotation for faster training
  translate: 0.1                # Translation
  scale: 0.4                    # Scaling (reduced)
  shear: 0.0                    # No shear
  perspective: 0.0              # No perspective
  flipud: 0.0                   # No vertical flip
  fliplr: 0.5                   # Standard horizontal flip
  
  # Albumentations augmentations
  use_albumentations: true
  random_brightness_contrast: true
  brightness_limit: 0.2
  contrast_limit: 0.2
  random_brightness_contrast_prob: 0.2
  blur: false
  cutout: true                  # Helps with robustness
  cutout_holes: 4               # Fewer holes
  cutout_height: 8
  cutout_width: 8
  cutout_prob: 0.3