# YOLO Neural Architecture Search Configuration with Complex Architecture Options

# Directories
directories:
  base_dir: .
  best_model_dir: best_model
  pruned_model_dir: pruned_models
  quantized_model_dir: quantized_models

# Dataset path
dataset_path: data.yaml

# Bayesian optimization settings
optimization:
  init_points: 2
  n_iter: 5
  performance_threshold: 0.85
  random_state: 42

# Search space definition - [min_value, max_value]
search_space:
  # Basic architecture parameters
  resolution: [320, 520]     # Input image size
  depth_mult: [0.33, 0.75]   # Depth multiplier (scaling of layers)
  width_mult: [0.25, 0.75]   # Width multiplier (scaling of channels)
  kernel_size: [3, 5]        # Kernel size for specific layers
  num_channels: [16, 128]    # Base number of channels
  
  # Training hyperparameters
  lr0: [1.0e-5, 1.0e-2]      # Initial learning rate
  momentum: [0.6, 0.98]      # Momentum for optimizer
  batch_size: [8, 16]        # Training batch size
  iou_thresh: [0.4, 0.9]     # IoU threshold for NMS
  weight_decay: [0.0001, 0.01] # Weight decay regularization
  
  # Advanced architecture options
  use_complex: [0, 1]        # Whether to use complex architecture options (0 or 1)
  activation: [0, 1, 2]      # 0=SiLU, 1=ReLU, 2=Mish
  use_cbam: [0, 1]           # Whether to use CBAM attention (0 or 1)
  dropout_rate: [0.0, 0.3]   # Dropout rate for regularization
  use_gating: [0, 1]         # Whether to use gated convolutions (0 or 1)
  bottleneck_ratio: [0.25, 0.5] # Channel reduction ratio in bottleneck blocks
  num_heads: [2, 4, 8]       # Number of attention heads
  skip_connections: [0, 1, 2] # 0=standard, 1=dense, 2=residual
  use_eca: [0, 1]            # Whether to use Efficient Channel Attention (0 or 1)

# Initial test configuration (used with --low-memory flag)
initial_test:
  resolution: 256
  depth_mult: 0.33
  width_mult: 0.25
  kernel_size: 3
  num_channels: 16
  lr0: 0.01
  momentum: 0.937
  batch_size: 4
  iou_thresh: 0.7
  weight_decay: 0.0005
  use_complex: 0
  activation: 0
  use_cbam: 0
  dropout_rate: 0.0
  use_gating: 0
  bottleneck_ratio: 0.25
  num_heads: 2
  skip_connections: 0
  use_eca: 0

# Training configuration
training:
  epochs: 5
  patience: 5
  optimizer: AdamW
  save: true
  verbose: true

# Pruning configuration
pruning:
  prune_amounts: [0.1, 0.2, 0.3]
  finetune: true
  finetune_epochs: 10

# Architecture transformation
activation_mapping:
  0: SiLU
  1: ReLU
  2: Mish
  3: LeakyReLU
  4: Hardswish
  5: PReLU

skip_connections_mapping:
  0: standard
  1: dense
  2: residual

# Data Augmentation Configuration
augmentation:
  # Basic YOLOv8 augmentations
  use_mosaic: true           # Use mosaic augmentation
  mosaic_prob: 1.0           # Probability of applying mosaic
  use_mixup: true            # Use mixup augmentation
  mixup_prob: 0.15           # Probability of applying mixup
  use_copy_paste: true       # Use copy-paste augmentation
  copy_paste_prob: 0.3       # Probability of applying copy-paste
  
  # Color and geometry transformations
  hsv_h: 0.015               # HSV Hue augmentation (0-1)
  hsv_s: 0.7                 # HSV Saturation augmentation (0-1)
  hsv_v: 0.4                 # HSV Value augmentation (0-1)
  degrees: 10.0              # Rotation degrees (0-180)
  translate: 0.2             # Translation (0-1)
  scale: 0.5                 # Scaling (0-1)
  shear: 2.0                 # Shear (0-10)
  perspective: 0.0001        # Perspective (0-0.001)
  flipud: 0.1                # Vertical flip (0-1)
  fliplr: 0.5                # Horizontal flip (0-1)
  
  # Advanced augmentations (requires albumentations library)
  use_albumentations: true
  
  # Blur and noise augmentations
  blur: true
  blur_prob: 0.1
  motion_blur: true
  motion_blur_prob: 0.1
  median_blur: true
  median_blur_prob: 0.1
  iso_noise: true
  iso_noise_prob: 0.1
  
  # Enhancement augmentations
  clahe: true
  clahe_prob: 0.1
  sharpen: true
  sharpen_prob: 0.1
  emboss: true
  emboss_prob: 0.1
  
  # Lighting augmentations
  random_brightness_contrast: true
  brightness_limit: 0.2
  contrast_limit: 0.2
  random_brightness_contrast_prob: 0.3
  random_gamma: true
  random_gamma_prob: 0.2
  random_shadow: true
  random_shadow_prob: 0.2
  
  # Regularization augmentations
  cutout: true
  cutout_holes: 8
  cutout_height: 8
  cutout_width: 8
  cutout_prob: 0.5